const PRODUCT = "BANANAS";
const POS_LIMIT = 20;
const REQUIRED_DAYS = ["Day -1", "Day 0", "Day 1"];
const TRACKED = ["Student", "MM Alpha", "MM Beta", "Momentum Hawk", "Reversion Owl"];
const RULES = {
  "MM Alpha": { limit: 12, role: "Maker / defensive" },
  "MM Beta": { limit: 20, role: "Maker / pressure" },
  "Momentum Hawk": { limit: 16, role: "Taker / momentum" },
  "Reversion Owl": { limit: 16, role: "Taker / mean rev" },
};
const DOT = { "Student": "ds", "MM Alpha": "d1", "MM Beta": "d2", "Momentum Hawk": "d3", "Reversion Owl": "d4", "Market": "dm" };
const PRIORITY = { student: 2, bot: 1, market: 0 };

let csvFiles = {}, dayOrder = [], strategySource = "", strategyFn = null;
let currentDayIdx = 0, currentStep = 0, totalSteps = 0, completedSteps = 0, runInterval = null;
let pnlChart = null, posChart = null, pnlHistory = [], posHistory = [];
let cash = 0, position = 0, agentState = {}, marketState = {}, bookSnapshot = null;
let pendingLogEntries = [], lastFair = 0, lastPnl = 0, lastTradePrice = null, lastTradeQty = null, lastTradeTimestamp = null, shownError = false, _seed = 42;

function rng(){_seed = (_seed * 1664525 + 1013904223) >>> 0; return _seed / 4294967295}
function resetRng(){_seed = 42}
function clamp(v,a,b){return Math.max(a, Math.min(b, v))}
function round2(v){return Math.round(v * 100) / 100}
function avg(arr,n=arr.length){const s = arr.slice(-n); return s.length ? s.reduce((x,y)=>x+y,0)/s.length : 0}
function diffStd(arr,n=30){const s=arr.slice(-(n+1)); if(s.length<3)return 0; const d=[]; for(let i=1;i<s.length;i++)d.push(s[i]-s[i-1]); const m=avg(d); return Math.sqrt(d.reduce((x,y)=>x+(y-m)*(y-m),0)/d.length)}
function parseDayKey(name){const m=String(name).toLowerCase().match(/day_(-?\d+)/); return m ? `Day ${parseInt(m[1],10)}` : null}
function deriveMid(row){const b=Number(row.bid_price_1), a=Number(row.ask_price_1); if(Number.isFinite(row.mid_price))return Number(row.mid_price); if(Number.isFinite(b)&&Number.isFinite(a))return (b+a)/2; if(Number.isFinite(b))return b; if(Number.isFinite(a))return a; return 0}
function blankAgents(){const out={}; for(const n of TRACKED)out[n]={cash:0,position:0,fills:0,tradedQty:0}; return out}
function resetCompetition(){agentState=blankAgents(); marketState={midHistory:[],fairHistory:[],lastMid:null}; pnlHistory=[]; posHistory=[]; cash=0; position=0; bookSnapshot=null; shownError=false; lastTradePrice=null; lastTradeQty=null; lastTradeTimestamp=null}
function syncStudent(){cash=agentState.Student.cash; position=agentState.Student.position}
function pnlOf(name,fair){const s=agentState[name]; return s.cash+s.position*fair}
function clipOrder(name,type,price,qty){if(!Number.isFinite(price)||!Number.isFinite(qty))return null; const s=agentState[name], limit=name==="Student"?POS_LIMIT:RULES[name].limit, allow=type==="bid"?Math.max(0,limit-s.position):Math.max(0,limit+s.position), size=Math.min(Math.max(0,Math.trunc(Math.abs(qty))),allow); return size>0?{type,price:Math.round(price),qty:size,from:name}:null}

function signals(row){
  const b1=Number(row.bid_price_1)||deriveMid(row)-3, a1=Number(row.ask_price_1)||deriveMid(row)+3, b2=Number(row.bid_price_2)||b1-1, a2=Number(row.ask_price_2)||a1+1, b3=Number(row.bid_price_3)||b2-1, a3=Number(row.ask_price_3)||a2+1;
  const bv1=Number(row.bid_volume_1)||1, av1=Number(row.ask_volume_1)||1, bv2=Number(row.bid_volume_2)||0, av2=Number(row.ask_volume_2)||0, bv3=Number(row.bid_volume_3)||0, av3=Number(row.ask_volume_3)||0;
  const mid=deriveMid(row), spread=Math.max(1,a1-b1), micro=(a1*bv1+b1*av1)/Math.max(1,bv1+av1), bidDepth=bv1+bv2+bv3, askDepth=av1+av2+av3;
  const imb1=(bv1-av1)/Math.max(1,bv1+av1), imb3=(bidDepth-askDepth)/Math.max(1,bidDepth+askDepth), anchor=marketState.midHistory.length?avg(marketState.midHistory,40):mid, mom=marketState.lastMid==null?0:mid-marketState.lastMid, meanRev=anchor-mid, vol=diffStd(marketState.midHistory,28);
  const fairRef=round2(mid + .85*(micro-mid) + 1.35*imb1 + .6*imb3 + .18*meanRev - .15*mom);
  const prevFair=marketState.fairHistory.length?marketState.fairHistory[marketState.fairHistory.length-1]:fairRef, fairTrend=fairRef-prevFair, fairEdge=fairRef-mid;
  return {b1,a1,b2,a2,b3,a3,bv1,av1,bv2,av2,bv3,av3,mid,spread,micro,imb1,imb3,anchor,mom,meanRev,vol,fairRef,fairTrend,fairEdge}
}

function remember(sig){marketState.midHistory.push(sig.mid); marketState.fairHistory.push(sig.fairRef); marketState.lastMid=sig.mid}
function mmAlpha(sig){const st=agentState["MM Alpha"], lean=.45*(sig.micro-sig.mid)+.75*sig.imb1+.2*sig.fairTrend, fair=sig.fairRef+lean-st.position*.34, half=clamp(1.3+.18*sig.spread+.55*sig.vol,1.2,3.6), size=clamp(5-Math.floor(Math.abs(st.position)/3),2,6); return [clipOrder("MM Alpha","bid",Math.min(sig.a1-1,Math.floor(fair-half)),size), clipOrder("MM Alpha","ask",Math.max(sig.b1+1,Math.ceil(fair+half)),size)].filter(Boolean)}
function mmBeta(sig){const st=agentState["MM Beta"], pressure=1.55*sig.fairEdge+1.1*(sig.micro-sig.mid)+1.8*sig.imb1+.75*sig.mom+.7*sig.fairTrend, fair=sig.fairRef+pressure-st.position*.16, half=clamp(1.8+.22*sig.spread+.9*sig.vol+Math.abs(sig.imb1)*2.1,1.8,4.9), size=clamp(5+Math.floor(Math.abs(pressure)*.65),4,9), orders=[clipOrder("MM Beta","bid",Math.min(sig.a1-1,Math.floor(fair-half)),size), clipOrder("MM Beta","ask",Math.max(sig.b1+1,Math.ceil(fair+half)),size)]; if(sig.fairRef>=sig.a1+1||pressure>2)orders.push(clipOrder("MM Beta","bid",sig.a1,2+Math.floor(rng()*3))); else if(sig.fairRef<=sig.b1-1||pressure<-2)orders.push(clipOrder("MM Beta","ask",sig.b1,2+Math.floor(rng()*3))); return orders.filter(Boolean)}
function momentumHawk(sig){const impulse=sig.mom+sig.fairTrend+1.6*sig.imb1, size=clamp(2+Math.floor(Math.abs(impulse)*1.4+Math.abs(sig.fairEdge)*.6),2,8); if(sig.fairRef>sig.a1||impulse>1.5)return [clipOrder("Momentum Hawk","bid",sig.a1+(sig.fairRef>sig.a1+2?1:0),size)].filter(Boolean); if(sig.fairRef<sig.b1||impulse<-1.5)return [clipOrder("Momentum Hawk","ask",sig.b1-(sig.fairRef<sig.b1-2?1:0),size)].filter(Boolean); return [clipOrder("Momentum Hawk","bid",Math.min(sig.a1-1,sig.b1+(sig.imb1>0?1:0)),1), clipOrder("Momentum Hawk","ask",Math.max(sig.b1+1,sig.a1-(sig.imb1<0?1:0)),1)].filter(Boolean)}
function reversionOwl(sig){const distToFair=sig.mid-sig.fairRef, distToAnchor=sig.mid-sig.anchor, size=clamp(2+Math.floor(Math.abs(distToFair)*.45+Math.abs(distToAnchor)*.15),2,8); if(distToFair>1.4||distToAnchor>2.2)return [clipOrder("Reversion Owl","ask",distToFair>3.2?sig.b1:Math.max(sig.b1+1,Math.ceil(sig.fairRef+.4)),size)].filter(Boolean); if(distToFair<-1.4||distToAnchor<-2.2)return [clipOrder("Reversion Owl","bid",distToFair<-3.2?sig.a1:Math.min(sig.a1-1,Math.floor(sig.fairRef-.4)),size)].filter(Boolean); return [clipOrder("Reversion Owl","bid",Math.min(sig.a1-1,Math.floor(sig.fairRef-1)),1), clipOrder("Reversion Owl","ask",Math.max(sig.b1+1,Math.ceil(sig.fairRef+1)),1)].filter(Boolean)}
function botOrders(sig){return [...mmAlpha(sig),...mmBeta(sig),...momentumHawk(sig),...reversionOwl(sig)]}

function buildBook(row,bots,student){const bids=[], asks=[]; for(let i=1;i<=3;i++){const bp=Number(row[`bid_price_${i}`]), bv=Number(row[`bid_volume_${i}`]), ap=Number(row[`ask_price_${i}`]), av=Number(row[`ask_volume_${i}`]); if(Number.isFinite(bp)&&bv>0)bids.push({price:bp,qty:bv,from:"Market",priority:PRIORITY.market}); if(Number.isFinite(ap)&&av>0)asks.push({price:ap,qty:av,from:"Market",priority:PRIORITY.market})} for(const o of bots)(o.type==="bid"?bids:asks).push({price:o.price,qty:o.qty,from:o.from,priority:PRIORITY.bot}); for(const o of student)(o.type==="bid"?bids:asks).push({price:o.price,qty:o.qty,from:"Student",priority:PRIORITY.student}); bids.sort((a,b)=>b.price-a.price||b.priority-a.priority); asks.sort((a,b)=>a.price-b.price||b.priority-a.priority); return {bids,asks}}
function snapBook(bids,asks){return {asks:asks.slice(0,8).map(o=>({...o})), bids:bids.slice(0,8).map(o=>({...o}))}}
function matchBook(bids,asks){const out=[]; while(bids.length&&asks.length){const bid=bids[0], ask=asks[0]; if(bid.price<ask.price)break; const qty=Math.min(bid.qty,ask.qty), price=ask.price; out.push({bidFrom:bid.from,askFrom:ask.from,price,qty}); bid.qty-=qty; ask.qty-=qty; if(bid.qty<=0)bids.shift(); if(ask.qty<=0)asks.shift()} return out}
function applyFill(name,side,price,qty){const s=agentState[name]; if(!s)return; if(side==="buy"){s.cash-=qty*price; s.position+=qty}else{s.cash+=qty*price; s.position-=qty} s.fills+=1; s.tradedQty+=qty}

function renderBoard(fair){const body=document.getElementById("competition-board-body"); body.innerHTML=""; const rows=TRACKED.map(name=>({name,role:name==="Student"?"Player":RULES[name].role,pnl:pnlOf(name,fair),position:agentState[name].position,cash:agentState[name].cash,fills:agentState[name].fills,qty:agentState[name].tradedQty})).sort((a,b)=>a.name==="Student"?-1:b.name==="Student"?1:b.pnl-a.pnl); for(const r of rows){const tr=document.createElement("tr"); if(r.name==="Student")tr.className="student-row"; const pc=r.pnl>0?"positive":r.pnl<0?"negative":"neutral"; tr.innerHTML=`<td><span class="dot ${DOT[r.name]}"></span>${r.name}</td><td>${r.role}</td><td class="${pc}">${r.pnl.toFixed(2)}</td><td>${r.position}</td><td>${r.cash.toFixed(2)}</td><td>${r.fills}</td><td>${r.qty}</td>`; body.appendChild(tr)}}
function renderBook(book){const ae=document.getElementById("book-asks"), be=document.getElementById("book-bids"); ae.innerHTML=""; be.innerHTML=""; if(!book)return; for(const o of book.asks.slice().reverse()){const d=document.createElement("div"); d.className=`row ask${o.from==="Student"?" student":""}`; d.innerHTML=`<span class="price">${o.price}</span><span class="owner">${o.from}</span><span class="qty">${o.qty}</span>`; ae.appendChild(d)} for(const o of book.bids){const d=document.createElement("div"); d.className=`row bid${o.from==="Student"?" student":""}`; d.innerHTML=`<span class="price">${o.price}</span><span class="owner">${o.from}</span><span class="qty">${o.qty}</span>`; be.appendChild(d)}}
function appendLog(entries){const body=document.getElementById("trade-log-body"); for(const e of entries){const tr=document.createElement("tr"), sc=e.side==="BUY"?"positive":"negative", pc=e.pnl>=0?"positive":"negative", cc=e.cashDelta>=0?"positive":"negative"; tr.innerHTML=`<td>${e.day}</td><td>${e.ts}</td><td class="${sc}">${e.side}</td><td>${e.price}</td><td>${e.qty}</td><td><span class="dot ${DOT[e.from]||"dm"}"></span>${e.from}</td><td class="${cc}">${e.cashDelta>=0?"+":""}${e.cashDelta.toFixed(2)}</td><td>${e.position}</td><td class="${pc}">${e.pnl.toFixed(2)}</td>`; body.prepend(tr); while(body.children.length>300)body.lastChild.remove()}}
function updateStats(fair){syncStudent(); const pnl=pnlHistory.length?pnlHistory[pnlHistory.length-1]:pnlOf("Student",fair||0), pe=document.getElementById("stat-pnl"), ce=document.getElementById("stat-cash"), po=document.getElementById("stat-pos"); pe.textContent=pnl.toFixed(2); pe.className=`sv ${pnl>0?"positive":pnl<0?"negative":"neutral"}`; ce.textContent=cash.toFixed(2); ce.className=`sv ${cash>0?"positive":cash<0?"negative":"neutral"}`; po.textContent=position; po.className=`sv ${position>0?"positive":position<0?"negative":"neutral"}`; document.getElementById("stat-fair").textContent=Number.isFinite(fair)?fair.toFixed(2):"-"; document.getElementById("stat-last-trade-price").textContent=Number.isFinite(lastTradePrice)?lastTradePrice.toFixed(2):"-"; document.getElementById("stat-last-trade-qty").textContent=Number.isFinite(lastTradeQty)?String(lastTradeQty):"-"; document.getElementById("stat-step").textContent=`${completedSteps} / ${totalSteps}`}
function initCharts(){if(pnlChart)pnlChart.destroy(); if(posChart)posChart.destroy(); const base={responsive:true,animation:false,plugins:{legend:{display:false}},scales:{x:{display:false},y:{ticks:{color:"#7086a4",font:{family:"Space Mono",size:9}},grid:{color:"rgba(255,255,255,.08)"}}}}; pnlChart=new Chart(document.getElementById("pnl-chart").getContext("2d"),{type:"line",data:{labels:[],datasets:[{data:[],borderColor:"#42e59d",backgroundColor:"rgba(66,229,157,.08)",borderWidth:1.8,pointRadius:0,fill:true,tension:.25}]},options:JSON.parse(JSON.stringify(base))}); posChart=new Chart(document.getElementById("pos-chart").getContext("2d"),{type:"line",data:{labels:[],datasets:[{data:[],borderColor:"#37c8ff",backgroundColor:"rgba(55,200,255,.08)",borderWidth:1.8,pointRadius:0,fill:true,tension:.25},{data:[],borderColor:"rgba(255,95,120,.45)",borderWidth:1,pointRadius:0,borderDash:[4,4]},{data:[],borderColor:"rgba(255,95,120,.45)",borderWidth:1,pointRadius:0,borderDash:[4,4]}]},options:JSON.parse(JSON.stringify(base))})}
function updateCharts(){if(!pnlChart||!posChart)return; const labels=Array.from({length:pnlHistory.length},(_,i)=>i); pnlChart.data.labels=labels; pnlChart.data.datasets[0].data=pnlHistory; pnlChart.update("none"); posChart.data.labels=labels; posChart.data.datasets[0].data=posHistory; posChart.data.datasets[1].data=Array(labels.length).fill(POS_LIMIT); posChart.data.datasets[2].data=Array(labels.length).fill(-POS_LIMIT); posChart.update("none")}
function updateProgress(){document.getElementById("progress-fill").style.width=(totalSteps>0?completedSteps/totalSteps*100:0)+"%"}
function syncActiveTab(){document.querySelectorAll(".tab").forEach((b,i)=>b.classList.toggle("active",i===currentDayIdx))}
function flushPendingLogs(){if(!pendingLogEntries.length)return; appendLog(pendingLogEntries); pendingLogEntries=[]}
function refreshUi(fair=lastFair){updateStats(fair); renderBoard(fair); renderBook(bookSnapshot); flushPendingLogs(); updateCharts(); updateProgress(); syncActiveTab()}
function advancePointer(){const rows=csvFiles[dayOrder[currentDayIdx]]||[]; return currentStep<rows.length}

function execStep(di,si,silent=false,renderNow=!silent){
  const day=dayOrder[di], row=(csvFiles[day]||[])[si]; if(!row)return;
  const enrichedRow={...row,hidden_fair:null,last_trade_price:lastTradePrice,last_trade_qty:lastTradeQty,last_trade_timestamp:lastTradeTimestamp}, ts=row.timestamp??"-";
  const sig=signals(enrichedRow), fair=sig.fairRef; enrichedRow.hidden_fair=fair;
  let student=[];
  try{const o=strategyFn(enrichedRow,position,si)||{}, bid=clipOrder("Student","bid",o.bid,o.bid_qty==null?0:o.bid_qty), ask=clipOrder("Student","ask",o.ask,o.ask_qty==null?0:o.ask_qty); student=[bid,ask].filter(Boolean)}
  catch(err){if(!silent&&!shownError){const el=document.getElementById("sim-error"); el.style.display="block"; el.textContent="Strategy error: "+err.message; shownError=true} student=[]}
  const built=buildBook(enrichedRow,botOrders(sig),student); bookSnapshot=snapBook(built.bids,built.asks); const matched=matchBook(built.bids,built.asks), studentTrades=[];
  for(const t of matched){applyFill(t.bidFrom,"buy",t.price,t.qty); applyFill(t.askFrom,"sell",t.price,t.qty); lastTradePrice=t.price; lastTradeQty=t.qty; lastTradeTimestamp=row.timestamp??null; syncStudent(); if(t.bidFrom==="Student")studentTrades.push({day,ts,side:"BUY",price:t.price,qty:t.qty,from:t.askFrom,cashDelta:-t.qty*t.price,position,pnl:pnlOf("Student",fair)}); else if(t.askFrom==="Student")studentTrades.push({day,ts,side:"SELL",price:t.price,qty:t.qty,from:t.bidFrom,cashDelta:t.qty*t.price,position,pnl:pnlOf("Student",fair)})}
  syncStudent(); lastPnl=pnlOf("Student",fair); lastFair=fair; pnlHistory.push(lastPnl); posHistory.push(position); remember(sig); if(studentTrades.length)pendingLogEntries.push(...studentTrades); if(!silent&&renderNow)refreshUi(fair)
}

function runStep(renderNow){if(!advancePointer())return false; execStep(currentDayIdx,currentStep,false,renderNow); completedSteps++; currentStep++; return true}
function getRunChunkSize(){const delay=parseInt(document.getElementById("speed-input").value,10)||0; if(delay===0)return 600; if(delay<=5)return 250; if(delay<=25)return 100; return 25}
function processRunChunk(){if(runInterval===null)return; let count=0,done=false,chunk=getRunChunkSize(); while(count<chunk){if(!runStep(false)){done=true; break} count++} refreshUi(lastFair); if(done){clearTimeout(runInterval); runInterval=null; document.getElementById("run-btn").textContent="Run All"; finishSimulation(); return} const delay=parseInt(document.getElementById("speed-input").value,10)||0; runInterval=setTimeout(processRunChunk,delay)}
function buildTabs(){const el=document.getElementById("day-tabs"); el.innerHTML=""; dayOrder.forEach((d,i)=>{const b=document.createElement("button"); b.className=`tab${i===currentDayIdx?" active":""}`; b.textContent=d; b.onclick=()=>{if(!runInterval)jumpToDay(i)}; el.appendChild(b)})}
function jumpToDay(idx){resetCompetition(); currentDayIdx=idx; currentStep=0; completedSteps=0; totalSteps=(csvFiles[dayOrder[idx]]||[]).length; resetRng(); document.getElementById("trade-log-body").innerHTML=""; pendingLogEntries=[]; const row=(csvFiles[dayOrder[idx]]||[])[0], previewRow=row?{...row,last_trade_price:null,last_trade_qty:null,last_trade_timestamp:null}:null, fair=previewRow?signals(previewRow).fairRef:0; updateStats(fair); renderBoard(fair); renderBook(null); updateCharts(); updateProgress(); syncActiveTab()}
function stepOnce(){if(!runStep(true))finishSimulation()}
function runAll(){const btn=document.getElementById("run-btn"); if(runInterval!==null){clearTimeout(runInterval); runInterval=null; btn.textContent="Run All"; return} btn.textContent="Pause"; runInterval=setTimeout(processRunChunk,0)}
function finishSimulation(){flushPendingLogs(); const p=pnlHistory.length?pnlHistory[pnlHistory.length-1]:0, el=document.getElementById("final-pnl-display"); el.textContent=(p>=0?"+":"")+p.toFixed(2); el.className=`final ${p>0?"positive":p<0?"negative":"neutral"}`; document.getElementById("final-banner").style.display="block"; window.scrollTo({top:0,behavior:"smooth"})}
function resetSim(){if(runInterval!==null){clearTimeout(runInterval); runInterval=null} document.getElementById("run-btn").textContent="Run All"; document.getElementById("setup-view").style.display="block"; document.getElementById("sim-view").style.display="none"; document.getElementById("final-banner").style.display="none"; document.getElementById("progress-fill").style.width="0%"; document.getElementById("trade-log-body").innerHTML=""; document.getElementById("competition-board-body").innerHTML=""; document.getElementById("sim-error").style.display="none"; pendingLogEntries=[]; lastFair=0; lastPnl=0; resetCompetition(); currentDayIdx=0; currentStep=0; completedSteps=0}
function numify(row){const out={}; for(const [k,v] of Object.entries(row)){const key=k.trim().toLowerCase().replace(/\s+/g,"_"), n=parseFloat(v); out[key]=Number.isNaN(n)?v:n} return out}
function refreshDays(){dayOrder=Object.keys(csvFiles).filter(d=>REQUIRED_DAYS.includes(d)).sort((a,b)=>parseInt(a.replace("Day ",""),10)-parseInt(b.replace("Day ",""),10)); document.getElementById("files-loaded").textContent=dayOrder.length?`Loaded: ${dayOrder.join(", ")}`:""}
function parseCsvFiles(files,target,requiredField,onDone){if(!files.length)return; let done=0; for(const f of files){const dayKey=parseDayKey(f.name); if(!dayKey){done++; if(done===files.length)onDone(); continue} Papa.parse(f,{header:true,skipEmptyLines:true,complete:res=>{const rows=res.data.map(numify).filter(r=>String(r.product||r.symbol||"").toUpperCase().includes(PRODUCT)); target[dayKey]=rows.filter(r=>r[requiredField]!=null); done++; if(done===files.length)onDone()}})}}
function handlePriceFiles(files){parseCsvFiles(files,csvFiles,"timestamp",refreshDays)}
function loadPy(src,name){const el=document.getElementById("py-loaded"); if(!/def\s+strategy\s*\(/.test(src)){el.style.color="var(--red)"; el.textContent="No strategy() function found"; strategySource=""; return} strategySource=src.trim(); el.style.color="var(--gold)"; el.textContent=`Loaded: ${name}`; document.getElementById("strategy-error").style.display="none"}

function py2js(src){
  src=src.replace(/"{3}[\s\S]*?"{3}/g,"").replace(/'{3}[\s\S]*?'{3}/g,"").replace(/#.*/g,"");
  src=src.split("\n").map(line=>{const lead=(line.match(/^(\s*)/)||["",""])[1], trimmed=line.trimStart(); if(/^[A-Za-z_]\w*\s*=/.test(trimmed)&&/\s+if\s+.+\s+else\s+/.test(trimmed)){const m=trimmed.match(/^(.+?)\s+if\s+(.+?)\s+else\s+(.+)$/); if(m){const eq=m[1].indexOf("="); if(eq!==-1){const left=m[1].slice(0,eq+1), val=m[1].slice(eq+1).trim(); return `${lead}${left} (${m[2].trim()} ? ${val} : ${m[3].trim()})`}}} return line}).join("\n");
  src=src.replace(/\bTrue\b/g,"true").replace(/\bFalse\b/g,"false").replace(/\bNone\b/g,"null").replace(/\band\b/g,"&&").replace(/\bor\b/g,"||").replace(/\bnot\b/g,"!").replace(/\bint\s*\(/g,"Math.trunc(").replace(/\bfloat\s*\(/g,"Number(").replace(/\babs\s*\(/g,"Math.abs(").replace(/\bmin\s*\(/g,"Math.min(").replace(/\bmax\s*\(/g,"Math.max(").replace(/\bround\s*\(/g,"Math.round(").replace(/\bprint\s*\(/g,"console.log(").replace(/row\[["'](\w+)["']\]/g,"row.$1").replace(/\belif\b/g,"else if");
  const lines=src.split("\n"), out=[], stack=[0], declared=new Set();
  for(const rawLine of lines){const raw=rawLine.trimEnd(); if(!raw.trim()){out.push(""); continue} const indent=raw.length-raw.trimStart().length, content=raw.trimStart(); while(stack.length>1&&stack[stack.length-1]>=indent){stack.pop(); out.push(`${" ".repeat(stack[stack.length-1])}}`)} const opener=/^(def |if |else if |else\s*$|else\s*:|for |while )/.test(content)&&raw.endsWith(":"); if(opener){let line=raw.slice(0,-1); line=line.replace(/^(\s*)def\s+(\w+)\s*\(([^)]*)\)\s*$/,"$1function $2($3)"); line=line.replace(/^(\s*)else\s*$/,"$1else"); line=line.replace(/^(\s*)(if|else if)\s+(.+)$/,(_,sp,kw,cond)=>`${sp}${kw} ${cond.trim().startsWith("(")?cond.trim():`(${cond.trim()})`}`); out.push(`${line} {`); stack.push(indent+1); continue} const assign=raw.match(/^(\s*)([A-Za-z_]\w*)\s*=[^=]/); if(assign&&!declared.has(assign[2])&&!/^(return|if|else|for|while|function)$/.test(assign[2])){declared.add(assign[2]); out.push(raw.replace(/^(\s*)([A-Za-z_]\w*)\s*=/,"$1let $2 ="))} else out.push(raw)}
  while(stack.length>1){stack.pop(); out.push("}")}
  return out.join("\n")
}

function compileStrategy(){
  const err=document.getElementById("strategy-error");
  try{const js=strategySource.includes("def strategy")?py2js(strategySource):strategySource; strategyFn=new Function("row","position","step",`${js}\nreturn strategy(row, position, step);`); const probe={bid_price_1:4898,ask_price_1:4904,bid_volume_1:9,ask_volume_1:11,bid_price_2:4897,ask_price_2:4905,bid_volume_2:7,ask_volume_2:7,bid_price_3:4896,ask_price_3:4906,bid_volume_3:4,ask_volume_3:4,mid_price:4901,timestamp:0,hidden_fair:4902,last_trade_price:null,last_trade_qty:null,last_trade_timestamp:null}; const result=strategyFn(probe,0,0); if(!result||typeof result!=="object")throw new Error("strategy() must return an object."); err.style.display="none"; return true}
  catch(e){err.style.display="block"; err.textContent="Strategy compile error: "+e.message; return false}
}
function validateInputs(){for(const day of REQUIRED_DAYS){if(!csvFiles[day]||!csvFiles[day].length){alert(`Missing BANANAS price file for ${day}.`); return false}} if(!strategySource){alert("Upload a Python strategy file first."); return false} return true}
function startSimulation(){if(!validateInputs())return; if(!compileStrategy())return; resetCompetition(); pendingLogEntries=[]; lastFair=0; lastPnl=0; lastTradePrice=null; lastTradeQty=null; lastTradeTimestamp=null; dayOrder=REQUIRED_DAYS.slice(); currentDayIdx=0; currentStep=0; completedSteps=0; totalSteps=(csvFiles[dayOrder[0]]||[]).length; resetRng(); document.getElementById("setup-view").style.display="none"; document.getElementById("sim-view").style.display="block"; document.getElementById("final-banner").style.display="none"; document.getElementById("sim-error").style.display="none"; document.getElementById("trade-log-body").innerHTML=""; buildTabs(); initCharts(); jumpToDay(0)}

document.getElementById("csv-input").addEventListener("change",e=>handlePriceFiles(e.target.files));
document.getElementById("py-input").addEventListener("change",e=>{const f=e.target.files[0]; if(!f)return; const r=new FileReader(); r.onload=ev=>loadPy(ev.target.result,f.name); r.readAsText(f)});
function wireDropZone(el,handler){el.addEventListener("dragover",e=>{e.preventDefault(); el.classList.add("drag-over")}); el.addEventListener("dragleave",()=>el.classList.remove("drag-over")); el.addEventListener("drop",e=>{e.preventDefault(); el.classList.remove("drag-over"); handler(e.dataTransfer.files)})}
wireDropZone(document.getElementById("drop-zone"),handlePriceFiles);
wireDropZone(document.getElementById("py-drop-zone"),files=>{const f=files[0]; if(!f)return; const r=new FileReader(); r.onload=ev=>loadPy(ev.target.result,f.name); r.readAsText(f)});
